### PR TITLE
disable some PHP from security page advices

### PR DESCRIPTION
**Pull request by mathieupotier**
added to exclusion : dl, apache_note, apache_setenv, show_source, virtual

### CODE REVIEW

**Comment by mathieupotier** [comment]
I don't know what the check-update expecting ...
updating the file in all docker/* images directory ?

**Comment by creekorful** [comment]
> I don't know what the check-update expecting ...
> 
> updating the file in all docker/* images directory ?

Exactly. To ensure consistency between images configuration.

**Comment by creekorful** [comment]
Hi @eldy, does the configuration looks good to you per Dolibarr recommendation?

Cheers

**Review by eldy — APPROVED** [review]

**Comment by eldy** [comment]
> Hi @eldy, does the configuration looks good to you per Dolibarr recommendation?
> 
> Cheers

Yes it does.

**Pull request merged**
